BASE_TASK_CONFIG_PATH: configs/tasks/rearrangepick_replica_cad_spa.yaml

SPA:
  VERBOSE: True
  RUN_FREQ: 4
  KINEMATIC_CTRL: True
  N_GRASPS: 100
  MP_OBJ: True
  MP_MARGIN: null
  MP_RENDER: True
  TIMEOUT: 3
  EXEC_EE_THRESH: 0.1
  # "Priv" or "Reg"
  MP_SIM_TYPE: "Priv"
  VIDEO_DIR: 'data/vids'
  DEBUG_DIR: "data/mp_test"
  COUNT_OBJ_COLLISIONS: True
  GRASP_GEN_IS_VERBOSE: True
VIDEO_DIR: "data/vids/"
VIDEO_OPTIONS: ["disk"]


COUNT_OBJ_COLLISIONS: True
COUNT_ROBOT_OBJ_COLLS: False
