ENVIRONMENT:
    MAX_EPISODE_STEPS: 200
DATASET:
    TYPE: None
TASK:
    TYPE: ExplTask-v0
    MAX_ACCUM_FORCE: 5000.0
    MAX_COLLISIONS: 2000.0
    FIX_BASE_TO_OBJ: None
    FORCE_BASED: True
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBO_OBJ_COLLS: False # TODO: check its impact

    # In radians
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05

    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False

    JOINT_SENSOR:
        TYPE: "JointSensor"
    EE_SENSOR:
        TYPE: "EeSensor"
    IS_HOLDING_SENSOR:
        TYPE: "IsHoldingSensor"
    LOCAL_SENSOR:
        TYPE: "LocalizationSensor"
    SENSORS: ["JOINT_SENSOR", "IS_HOLDING_SENSOR", "EE_SENSOR", "LOCAL_SENSOR"]
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    MEASUREMENTS:
        - "END_EFFECTOR_TO_OBJECT_DISTANCE"
    POSSIBLE_ACTIONS:
        - STOP
        - MOVE_FORWARD
        - TURN_LEFT
        - TURN_RIGHT

SIMULATOR:
    ACTION_SPACE_CONFIG: v0 # TODO: change
    AC_FREQ_RATIO: 4 
    AGENTS: ['AGENT_0']
    AGENT_0:
        ANGULAR_ACCELERATION: 12.56
        ANGULAR_FRICTION: 1.0
        COEFFICIENT_OF_RESTITUTION: 0.0
        HEIGHT: 1.5
        IS_SET_START_STATE: True
        LINEAR_ACCELERATION: 20.0
        LINEAR_FRICTION: 0.5
        MASS: 32.0
        RADIUS: 0.1
        SENSORS: ['HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'ARM_RGB_SENSOR', 'ARM_DEPTH_SENSOR']
        START_POSITION: [0.0, 0.0, 1.0]
        START_ROTATION_AXIS: [0.0, 1.0, 0.0]
        START_ROTATION_DEG: 90
    HEAD_RGB_SENSOR:
        WIDTH: 512
        HEIGHT: 512
        POSITION: [0.0, 1.5, 0.0]
        ORIENTATION: [0.0, 0.0, 0.0]
        UUID: 'robot_head_rgb'
    HEAD_DEPTH_SENSOR:
        WIDTH: 512
        HEIGHT: 512
        POSITION: [0.0, 1.5, 0.0]
        ORIENTATION: [0.0, 0.0, 0.0]
        UUID: 'robot_head_depth'
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    ARM_DEPTH_SENSOR: # TODO: modify arm height
        WIDTH: 512
        HEIGHT: 512
        UUID: 'robot_arm_depth'
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
    ARM_RGB_SENSOR:
        HEIGHT: 512
        WIDTH: 512
        UUID: 'robot_arm_rgb'
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    # TODO: add third person sensor
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    EXPL_SIM:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    HIGH_RES_DIM: 512
    LAG_OBSERVATIONS: 2 # not sure what this is
    POV: 1st
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    SEED: 100
    SCENE_ID: datasets/ReplicaCAD/configs/scenes/apt_0.scene_instance.json
    SCENE_DATASET: datasets/ReplicaCAD/replicaCAD.scene_dataset_config.json
    SCENE_LIGHT_SETUP: datasets/ReplicaCAD/configs/lighting/frl_apartment_0.lighting_config.json
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: ExplSim 

# TODO: check for pyrobot

